spring.application.name=documind

spring.datasource.url=jdbc:postgresql://localhost:5432/documind
spring.datasource.username=documind
spring.datasource.password=documind

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ============================================================
# Multipart File Upload Configuration
# ============================================================

# Maximum size of a single uploaded file.
spring.servlet.multipart.max-file-size=10MB

# Maximum size of the complete multipart request.
spring.servlet.multipart.max-request-size=12MB

#===========================================================
#Setting Gemini Key
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}