package com.documind.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.Array;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "document_chunks")
@Getter
@Setter
@NoArgsConstructor
public class DocumentChunk {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The document this chunk belongs to.
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "document_id", nullable = false)
    private Document document;

    // Position of this chunk inside the original document.
    @Column(nullable = false)
    private Integer chunkIndex;

    // Actual text extracted from the document.
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /*
     * Semantic embedding generated by Gemini.
     *
     * Hibernate 7 has native support for vector types.
     *
     * Gemini currently produces 3072-dimensional embeddings.
     *
     * PostgreSQL:
     *
     *     vector(3072)
     */
    @JdbcTypeCode(SqlTypes.VECTOR)
    @Array(length = 3072)
    @Column(columnDefinition = "vector(3072)")
    private float[] embedding;
}